### ISSUE TITLE
Handler interface?

### ISSUE THREAD

**Issue by rtheunissen** [guzzle/RingPHP#31]
I was just wondering why the handlers don't use a common interface? That way if a library uses Guzzle and want to give the option to use an alternative handler, they can just accept for example a RingHandlerInterface object. This has come as somewhat of a requirement due to clients now being immutable. I want to create a Guzzle client with some internal options, but also give the user an option to specify a different handler. What's the best way to do this if an interface doesn't exist?

**Comment by rtheunissen** [comment]
I'm setting a baseUrl internally when creating the Client, so I don't have the option of setting a different handler elsewhere.

**Comment by mtdowling** [comment]
RingPHP handlers are just PHP callables. An interface for a single method wouldn't add any value IMO and would make it harder to compose handlers.

I would just typehint on callable and document that it needs to adhere to a ringphp method signature.

**Comment by rtheunissen** [comment]
> RingPHP handlers are just PHP callables. 

But a callable isn't necessarily a RingPHP handler. An interface with a single method makes perfect sense, even an interface with no methods can serve a purpose. I don't think it's good to judge whether an interface is necessarily partly on how many methods it would contain. 

Type hinting callable and relying on documentation is in my opinion much weaker than using an interface. It takes longer to decipher the behaviour and means I can't be sure that the callable passing in is actually an implemented RingPHP handler.

 > would make it harder to compose handlers

Wouldn't it make it easier? You know you have a single method to implement and it's clearly documented how to do that. Maybe not easier but can't see it be any harder either. 

This feels like a similar argument to returning an object vs an array combined with list() for multiple return values. The array / list() way feels manual, low-level and fragile. The object has defined behaviour and parameter order doesn't matter like it would with list(). This is just an example but I feel like it's on par with this situation: it feels primitive to pass callables around.

**Comment by rtheunissen** [comment]
> **What's the best way to do this if an interface doesn't exist?**

**Comment by mtdowling** [comment]
> I don't think it's good to judge whether an interface is necessarily partly on how many methods it would contain.

You're right, it's not always an indication of an unnecessary interface. When I see an interface with a single method, I'm always reminded of this talk: https://www.youtube.com/watch?v=o9pEzgHorH0

> Wouldn't it make it easier? You know you have a single method to implement and it's clearly documented how to do that. Maybe not easier but can't see it be any harder either.

It would not be easier because you lose functional composition. By forcing handlers to be an interface, you'd need to implement a class each time you want to decorate a handler. Functional composition allows ad hoc handlers to be defined inline without the need for a new class.

RingPHP is designed to be a single function and does not require an interface. Using the `__invoke` method method and requiring an interface loses the benefit of the `__invoke` method (allowing an object to be a `callable`). By forcing an interface, we lose function composition for the handlers as you would now have to create a class for each decorator.

**Comment by rtheunissen** [comment]
That makes sense, thanks for explaining. :) Why do you say that an interface loses the benefit of the object being a callable? Isn't it still a callable?
